openapi: 3.1.0
info:
  title: tiny.sibr.dev
  version: '1.0'
  description: SIBR's url shortener
servers:
  - url: 'https://tiny.sibr.dev'
paths:
  /submit:
    post:
      summary: ''
      operationId: post-submit
      responses:
        '200':
          description: |
            shortened url token
      description: shorten url
  '/{token}':
    parameters:
      - schema:
          type: string
        name: token
        in: path
        required: true
        description: shortened url token
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '302':
          description: Found
          headers:
            Location:
              schema:
                type: string
              description: original url
      operationId: get-token
      description: redirects to url from shortened version
  '/lookup/{token}':
    parameters:
      - schema:
          type: string
        name: token
        in: path
        required: true
        description: shortened url token
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: returns original url
      operationId: get-lookup-token
      description: returns original URL from shortened url token
