openapi: 3.1.0
info:
  title: tiny.sibr.dev
  version: '1.0'
  description: SIBR's url shortener
servers:
  - url: 'https://tiny.sibr.dev'
paths:
  /submit:
    post:
      summary: shorten url
      operationId: submit
      description: shorten url
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                url:
                  type: string
            examples: {}
          application/json:
            schema:
              type: object
              properties: {}
            examples:
              example-1:
                value: {}
        description: url to shorten
      responses:
        '200':
          description: shortened url token
          content:
            text/plain:
              schema:
                type: string
              examples: {}
  '/{token}':
    parameters:
      - schema:
          type: string
        name: token
        in: path
        required: true
        description: shortened url token
    get:
      summary: redirect to original url
      tags: []
      responses:
        '302':
          description: Found
          headers:
            Location:
              schema:
                type: string
              description: original url
      operationId: get-token
      description: redirects to url from shortened version
  '/lookup/{token}':
    parameters:
      - schema:
          type: string
        name: token
        in: path
        required: true
        description: shortened url token
    get:
      summary: lookup original url from token
      tags: []
      responses:
        '200':
          description: body containing original URL
      operationId: get-lookup-token
      description: returns original URL from shortened url token
